### ISSUE TITLE
"expectMockFnsCalledWith" not asserting inner function argument

### ISSUE THREAD

**Issue by paraniraja** [nossbigg/jest-mock-curry-fn#1]
Thanks for sharing this utility.

in the example provided, 

```mockStringPrefixerFn.expectMockFnsCalledWith('first')('second');``` 

inner function argument `second` is not asserted. If I change the value to `third`, test is passed.

Thanks

**Comment by paraniraja** [comment]
I believe issue is due to 
https://github.com/nossbigg/jest-mock-curry-fn/blob/main/src/makeMockCurryFn/utils/makeExpectCurriedMockFns.ts#L8

**Comment by nossbigg** [comment]
@paraniraja thanks for spotting this error, really do appreciate it! 🙇  

I've landed an MR for the fix (https://github.com/nossbigg/jest-mock-curry-fn/pull/2), and I've published a new version of the package `v0.0.2` 👍

Hope you like the fix! 🙂
